on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        template: ./main.bicep
        parameters: 'resourceGroupName=gh-actions-rg-unique'
        failOnStdErr: false